server:
  port: 8888  # Gateway and Eureka Server will run on this port



spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/inventory/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
    discovery:
      locator:
        enabled: true  # Enables dynamic service discovery for routes
        lower-case-service-id: true

eureka:
  client:
    register-with-eureka: false  # This service is the Eureka Server
    fetch-registry: false        # No need to fetch registry since it's the server
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 60000
