server:
  port: 9000  # Gateway and Eureka Server will run on this port



spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    netty:
      prefer-native: false
    gateway:
      routes:
        - id: inventory-service
          uri: http://localhost:8085
          predicates:
            - Path=/inventory/**
        - id: order-service
          uri: http://localhost:8086
          predicates:
            - Path=/order/**
        - id: payment-service
          uri: http://localhost:8087
          predicates:
            - Path=/payment/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
      fetch-registry: true
      register-with-eureka: true

logging:
  level:
    root: INFO
#    org.springframework.cloud.gateway: DEBUG    # Gateway core logs
#    org.springframework.cloud.loadbalancer: DEBUG  # LoadBalancer logs
#    com.netflix.eureka: DEBUG  # Eureka logs
#    reactor.netty: DEBUG  # Netty logs for troubleshooting network issues


